name: segmentation_tf
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy=1.23.5
  - pandas
  - scikit-image
  - scipy
  - tifffile
  - opencv
  - imageio
  - pillow
  - zarr
  - openslide
  - openslide-python
  - pyvips
  - h5py
  - tqdm
  - matplotlib
  # On Linux with NVIDIA GPU:
  - tensorflow=2.11.*
  - pip:
      - keras-unet-collection==0.1.13
