name: omics-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - jupyter
  - ipykernel 
  - pip
  - pip:
      - gseapy
      - matplotlib-venn
